services:
  - type: web
    name: thuongmaidientu
    env: php
    plan: free
    region: singapore
    buildCommand: |
      bash deploy.sh
    startCommand: php artisan serve --host 0.0.0.0 --port 10000