services:
  - type: web
    name: thuongmaidientu
    env: php
    plan: free
    region: singapore
    buildCommand: |
      bash deploy.sh
    startCommand: php -S 0.0.0.0:$PORT -t public public/index.php