services:
  - type: web
    name: thuongmaidientu
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
  - type: worker
    name: thuongmaidientu-release
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: "php artisan migrate --force"